version: "3.9"
services:
  shmem:
    image: debian:buster-slim
    command: ["sleep", "infinity"]
    shm_size: 6gb
    ipc: shareable
  db:
    image: mariadb:10.5
    environment:
      TZ: "America/Los_Angeles"
      MYSQL_DATABASE: "zm"
      MYSQL_USER: "${USER_NAME}"
      MYSQL_PASSWORD: "${USER_PASS}"
      MYSQL_ROOT_PASSWORD: "${ROOT_PASS}"
    volumes:
      - db:/var/lib/mysql
  zm:
    build:
      context: ./zm
      args:
        version: "${ZM_VERSION}"
    image: pdulion/zm:${ZM_VERSION}
    ipc: service:shmem
    environment:
      TZ: 'America/Los_Angeles'
      ZM_DB_HOST: db
      ZM_DB_NAME: zm
      ZM_DB_USER: "${USER_NAME}"
      ZM_DB_PASS: "${USER_PASS}"
    volumes:
      - zm-tmp:/tmp/zm
      - zm-run:/var/run/zm
      - zm-log:/var/log/zm
      - zm-data:/var/cache/zoneminder
    depends_on:
      - shmem
      - db
  zm-web:
    build:
      context: zm-web
      args:
        version: "${ZM_VERSION}"
    image: pdulion/zm-web:${ZM_VERSION}
    ipc: service:shmem
    ports:
      - "8080:80"
    environment:
      TZ: 'America/Los_Angeles'
      ZM_DB_HOST: db
      ZM_DB_NAME: zm
      ZM_DB_USER: "${USER_NAME}"
      ZM_DB_PASS: "${USER_PASS}"
    volumes:
      - zm-tmp:/tmp/zm
      - zm-run:/var/run/zm
      - zm-log:/var/log/zm
      - zm-data:/var/cache/zoneminder
    depends_on:
      - shmem
      - db
      - zm
volumes:
  db:
  zm-tmp:
  zm-run:
  zm-log:
  zm-data:
