#!/bin/bash
set -e

# Remove old pid files
rm -rf /run/zm/*

export MYSQL_PWD="${ZM_DB_PASS}"
if [[ ! $(mysql --host=${ZM_DB_HOST} --user=${ZM_DB_USER} --database=zm --execute="SHOW TABLES LIKE 'Config'") ]]; then
  mysql --host=${ZM_DB_HOST} --user=${ZM_DB_USER} --database=zm < /usr/share/zoneminder/db/zm_create.sql
else
  /usr/bin/zmupdate.pl
fi
/user/bin/zmpkg.pl start

# Monitor zoneminder and shutdown safely
function on_term {
    echo "Shutting down zoneminder..."
    /user/bin/zmpkg.pl stop || true
}
trap 'on_term' SIGINT SIGTERM EXIT
while pgrep -F /run/zm/zm.pid &>/dev/null
    sleep 5
done
