#!/bin/bash
set -e

echo "Setting the timezone: $TZ"
if [[ $(cat /etc/timezone) != $TZ ]] ; then
	echo "$TZ" > /etc/timezone
	ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
	DEBIAN_FRONTEND=noninteractive dpkg-reconfigure tzdata
fi

# Configure zoneminder from ZM_* environment variables and start
re='^ZM_'
while IFS='=' read -r key value ; do
  if [[ $key =~ $re ]] ; then
    sed  -i "s/$key=.*/$key=$value/" /etc/zm/zm.conf
  fi
done < <(env)
